export const Theme = {
  colors: {
    primary: "#D97757",
    primaryBright: "#F0956D",
    primaryDim: "#A85A3E",
    accent: "#E8A87C",
    secondary: "#5C5C5C",
    success: "#2E8F66",
    successBright: "#45C98E",
    error: "#B07D7D",
    errorBright: "#D9A0A0",
    warning: "#C9A052",
    text: "#E6E6E6",
    dim: "#737373",
    dimmer: "#4A4A4A",
    highlight: "#FFFFFF",
    info: "#4A9EFF",
    infoDim: "#3A7ACC",
    glow: "#FFB088",
    shadow: "#3D2E25",
    gradientWarm: ["#D97757", "#E8A87C", "#F0C4A8", "#E8A87C", "#D97757"],
    gradientCool: ["#4A9EFF", "#6DB5FF", "#99CCFF", "#6DB5FF", "#4A9EFF"],
    gradientBorder: ["#D97757", "#A85A3E", "#5C5C5C", "#A85A3E", "#D97757"],
  },
  symbols: {
    arrow: ">",
    bullet: "•",
    tick: "✓",
    cross: "✗",
    pointer: "❯",
    pointerSmall: "›",
    line: "─",
    doubleLine: "═",
    corner: {
      topLeft: "╭",
      topRight: "╮",
      bottomLeft: "╰",
      bottomRight: "╯",
    },
    vertical: "│",
    horizontal: "─",
    dot: "·",
    ellipsis: "…",
    star: "✦",
    diamond: "◆",
    diamondSmall: "◇",
    circle: "●",
    circleOpen: "○",
    circleDot: "◉",
    spinner: ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"],
    pulse: ["░", "▒", "▓", "█", "▓", "▒", "░"],
    wave: ["~", "≈", "~", " "],
    breathe: ["·", "•", "●", "•", "·"],
    glow: ["✧", "✦", "✧"],
  },
  spacing: {
    small: 1,
    medium: 2,
    large: 4,
  },
  animation: {
    spinnerInterval: 80,
    pulseInterval: 150,
    gradientInterval: 200,
    breatheInterval: 300,
  },
} as const;

export type ThemeColors = typeof Theme.colors;
export type ThemeSymbols = typeof Theme.symbols;
